Primer intento
luistf24/Trozo-de-panceta pull request #1
Opened 2022-09-16 08:05 UTC by luistf24

Objetivo 0

2022-09-16 12:11 UTC, JJ commented
Por favor, mira la lista de comprobación que hay en el guión, copia, pega, y actúa.

2022-09-17 11:20 UTC, luistf24 commented
Buenas, he cambiado la idea del proyecto dado que la anterior parece muy complicada de realizar. He mirado y hay un par de APIs públicas que facilitarán mucho el trabajo a la hora de implementar la práctica, pero no sé si la idea es suficiente.

2022-09-17 16:44 UTC, JJ commented
En el guión os dice que razonéis la respuesta un poco más allá de marcarla. Voy a revisarlo, pero en general la respuesta a las preguntas te guía o no sobre si se ha alcanzado el objetivo

2022-09-17 16:46 UTC, JJ requested changes
Supongo que puede ser en la nube si los datos se obtienen a partir de un API, pero el resto deberías tratar de mejorarlo.

2022-09-17 16:46 UTC, JJ commented on README.md
> +Trozo de panceta es una aplicación que busca ayudar a las familias a reducir el gasto diario en el consumo de la luz.
No es una aplicación, tienes que describir un problema.

2022-09-17 16:46 UTC, JJ commented on README.md
> +Los principales clientes serán los usuarios de la aplicación.
Esto no es una lógica de negocio. Ni veo la lógica de negocio, más allá de ver mínimos a lo largo del día.

2022-09-17 18:07 UTC, luistf24 commented on README.md
> +Los principales clientes serán los usuarios de la aplicación.
He modificado la lógica de negocio, que no me había quedado muy clara

2022-09-18 16:15 UTC, JJ requested changes
Tampoco está claro qué aporta que esté en Internet, porque los datos o acciones de unos usuarios no van a beneficiar a otros. Consultar un API y dar un resultado se puede hacer localmente desde un app o hasta el navegador.

2022-09-18 16:15 UTC, JJ commented on README.md
> +Trozo de panceta es una aplicación que busca ayudar a las familias a reducir el gasto diario en el consumo de la luz.
No has contestado a esto ni o has cambiado

2022-09-18 16:15 UTC, JJ commented on README.md
> +Los principales clientes serán los usuarios de la aplicación los cuales pagaran una mensualidad por el uso de esta.
Sigue siendo una búsqueda del mínimo. Si es algo que puede hacer una persona buscando en Internet el precio y decidiendo qué electrodoméstico poner, no veo qué valor se puede aportar.

2022-09-18 18:44 UTC, luistf24 commented on README.md
> +Los principales clientes serán los usuarios de la aplicación los cuales pagaran una mensualidad por el uso de esta.
También actuaría como un planificador de actividades, la idea es que te genere una planificación con los distintos electrodomésticos que tienes que poner ese día, marques los que utilices y con los que has marcado te vaya generando una aproximación de cuanto ha costado.

2022-09-19 12:46 UTC, JJ commented on README.md
> +Los principales clientes serán los usuarios de la aplicación los cuales pagaran una mensualidad por el uso de esta.
¨Actuaría como" no describe un problema. Por favor, piensa en el problema.

2022-09-24 09:11 UTC, luistf24 commented on README.md
> +Los principales clientes serán los usuarios de la aplicación los cuales pagaran una mensualidad por el uso de esta.
Buenas, está listo para revisión

2022-09-24 09:37 UTC, JJ commented on README.md
> +Los principales clientes serán los usuarios de la aplicación los cuales pagaran una mensualidad por el uso de esta.
Generalmente, cuando se hacen comentarios sobre una línea, se cierra el comentario si se han hecho cambios. No parece que hayas hecho ninguno aquí, donde se ha solicitado. Reviso en todo caso.

2022-09-24 09:39 UTC, JJ requested changes
Ya os comenté en clase que lo hablado se me puede olvidar o no. Sigues sin especificar la lógica de negocio que hablamos, ni aclarar cuando se obtienen los datos, ni qué problema hay. Por favor, hazlo, revisando las líneas donde se han hecho comentarios.

2022-09-24 10:39 UTC, luistf24 commented
He modificado la lógica de negocio

2022-09-25 08:03 UTC, JJ approved these changes
Sigues sin poner lo que hablamos, es decir, buscar tramos consecutivos de dos o más horas para poner electrodomésticos que tengan esa duración. Pero la regresión para averiguar lo que va a ocurrir en la semana me vale. En todo caso puedes decidir una o las dos cosas más adelante, en productos mínimamente viables sucesivos.

2022-09-25 08:03 UTC, JJ commented on README.md
> +- Su ubicación
También podrías especificar que se trata de península, Baleares, Ceuta y Melilla, como hablamos.

2022-09-25 10:11 UTC, merged