[IV-22-23] Objetivo 1
luistf24/Trozo-de-panceta pull request #2
Opened 2022-10-03 08:14 UTC by luistf24

2022-10-03 20:13 UTC, luistf24 commented
> Hola! La github action me ha asignado como revisor aleatorio, espero serte útil tada
> 
> Lo primero que te diría es que metas las historias de usuario y las personas también en la carpeta docs/ ya que eso es lo que va a mirar JJ, o al menos lo que más fácil le va a resultar ver porque así se ven en el apartado "Files changed" del PR smile

Me pongo con elol, muchas gracias!! :ok_hand: :ok_hand:

2022-10-03 21:25 UTC, delightfulagony commented
Genial! Le echo un ojo a todo y te comento ^^

2022-10-03 21:52 UTC, delightfulagony requested changes

2022-10-03 21:52 UTC, delightfulagony commented on docs/milestones.md
> +* [ ] **[M6]:** Función que indique gasto de la luz aproximado del día
Los milestones deberían estar ordenados de forma lógica, ¿cómo vas a generar un planning de los electrodomésticos si no sabes nada acerca de los electrodomésticos ni de los precios?

Lo primero (y que es también la siguiente práctica) debería ser diseñar las estructuras que van a contener la información que usa la aplicación.
```suggestion
* [ ] **[M0]:** Crear estructura de datos para los electrodomésticos (Tipo, Marca, Consumo...)    
* [ ] **[M1]:** Crear estructura de datos tramo horario(hora, lista electrodomésticos, precio tramo, gasto aproximado)  
* [ ] **[M2]:** Crear base de datos para almacenar el precio de la luz en distintos tramos diarios    
* [ ] **[M3]:** Crear base de datos para almacenar la información de los distintos electrodomésticos de los usuarios    
* [ ] **[M4]:** Función para generar un plannig de los electrodomésticos con los datos inferidos ( si el día ha pasado no lo incluye)
* [ ] **[M5]:** Función para generar el planning de un día óptimo (Se ejecutaría una vez cada día para modificar los electrodomésticos que se ponen en un tramo de ese día y volvería a ejecutar M0)   
* [ ] **[M6]:** Función que indique gasto de la luz aproximado del día    
```

También, creo que el [M3] y el [M4] quizá podrían dejarse para más adelante ya que me parece más interesante para tu proyecto el generar un planning que simplemente almacenar unos datos que ya estarás obteniendo de una fuente pública, aunque eso ya es decisión tuya.

2022-10-03 21:52 UTC, delightfulagony commented on docs/personas.md
> +Tiene una familia numerosa, es muy consciente de la importancia del ahorro.
Estas 3 personas son tan similares que probablemente podrían fusionarse en una sola, ya que el uso que van a hacer de la aplicación y sus características personales son las mismas de acuerdo con lo descrito.

2022-10-03 21:52 UTC, delightfulagony commented on docs/user-stories.md
> +- [HU1] Los usuarios quieren saber exactemente que electrodomésticos poner ese día
No veo una diferencia clara entre [HU0] y [HU1], ¿el [HU0] se refiere a cuando poner los electrodomésticos en un día concreto y el [HU1] se refiere a qué día de la semana por ejemplo poner una lavadora?

2022-10-03 21:52 UTC, delightfulagony commented on docs/user-stories.md
> +	- [HU4] Luis quiere saber cuando poner los electrodomésticos para ahorrar
Aquí me pasa un poco igual que con las personas, [HU0] y [HU4] son la misma historia de usuario.

2022-10-03 21:52 UTC, delightfulagony commented on docs/user-stories.md
> +	- [HU5] Hortensia quiere saber a que hora le va a salir barato cocinar la cena
Hay algunas cosas que se repiten, dijo JJ en clase que no pasaba nada por tener sólo 1 o 2 historias de usuario, que no por poner más iba a estar mejor. Tu aplicación tiene un propósito bastante claro y a mi parecer es normal que no tengas mil historias de usuario distintas, basta con hacer algo y hacerlo bien :smiley:

2022-10-03 21:52 UTC, delightfulagony commented on docs/milestones.md
> +* [ ] **[M6]:** Función que indique gasto de la luz aproximado del día
Falta también que pongas qué determina si un milestone está bien, qué es lo que lo comprueba si "es viable". 

Básicamente este apartado de la lista
- [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?

2022-10-03 22:32 UTC, luistf24 commented on docs/user-stories.md
> +- [HU1] Los usuarios quieren saber exactemente que electrodomésticos poner ese día
En [HU0] se tira de la predicción del precio de los tramos que se genera con los datos acumulados  que puede ser inexacta, mientras que todos los días sale el precio exacto del tramo por lo que en [HU1] se busca una planificación óptima para ese día. Lo modifico porque la verdad es que no queda muy  claro

2022-10-04 15:49 UTC, luistf24 commented on docs/user-stories.md
> +	- [HU5] Hortensia quiere saber a que hora le va a salir barato cocinar la cena
Buenas!! Ya he modificado lo que me dijiste, era a eso a lo que te referías?

2022-10-05 14:50 UTC, delightfulagony requested changes

2022-10-05 14:50 UTC, delightfulagony commented on docs/milestones.md
> +* [ ] **[M6]:** Función que indique gasto de la luz aproximado del día
Sigue sin poner qué hace un milestone viable, ¿qué requisitos tiene que cumplir el proyecto en cada milestone?
Por ejemplo, ¿qué información hace falta en el M0 para que se considere correcto?

2022-10-05 14:50 UTC, delightfulagony commented on docs/user-stories.md
> +	- [HU3] Félix quiere saber al despertarse a que hora tiene que poner la lavadora ese día
Me explicaste las diferencias entre HU0 y HU1 pero no las has reflejado en el texto, deberías aclarar por qué son distintos, ya sea cambiando cómo está escrito o poniendole una descripción

2022-10-11 13:37 UTC, delightfulagony approved these changes
Yo lo veo guay. :partying_face: 
[Recuerda poner en cada commit por qué haces el cambio, el porqué de los cambios es lo más interesante y en general seguir las buenas prácticas de git](https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines)
Si tú estás también conforme con el PR menciona a JJ con la @ para que lo revise. :balloon:

2022-10-11 14:22 UTC, luistf24 commented
Buenas @JJ , listo para revisión

2022-10-11 15:25 UTC, JJ requested changes
Las HUs son (más o menos) correctas, salvo lo indicado, pero deberás echarle un vistazo al concepto de milestone como producto mínimamente viable.

2022-10-11 15:25 UTC, JJ commented on docs/milestones.md
> +* [ ] **[M0]:** Crear estructura de datos para los electrodomésticos
Una estructura de datos no es un producto. Consulta el guión, por favor. También lo dijimos en clase.

2022-10-11 15:25 UTC, JJ commented on docs/milestones.md
> +	* Esta estructura encapsula toda la información necesaria de un electrodoméstico, tipo de electrodoméstico, modelo, marca y consumo medio
Tampoco incluye ningún detalle de implementación.

2022-10-11 15:25 UTC, JJ commented on docs/milestones.md
> +	* Esta estructura contendrá hora, lista electrodomésticos, precio tramo, gasto aproximado
La división y secuenciación de estos dos milestones es arbitraria. Tampoco corresponde a un PMV, e incluye detalles de implementación.

2022-10-11 15:25 UTC, JJ commented on docs/user-stories.md
> +- [HU0] Los usuarios quieren saber cuando poner los electrodomésticos para ahorrar dinero a lo largo de la semana.
No existe el 0 en las HUs. Consulta los errores frecuentes en el guión de la semana 5.

2022-10-11 15:25 UTC, JJ commented on docs/user-stories.md
> +	- [HU4] Mario quiere saber cuando poner las máquinas que realizan tareas automáticas para ahorrar
No sé en qué sentido "hacer tareas automáticas" afecta a la lógica de negocio. Si no lo hace, no sería una HU.

2022-10-11 15:25 UTC, JJ commented on docs/milestones.md
> +* [ ] **[M6]:** Función que indique gasto de la luz aproximado del día
Esto no lo has contestado.

2022-10-11 17:35 UTC, luistf24 commented
Buenas @JJ , ya he corregido las historias de usuario y he modificado los milestones.

2022-10-12 07:23 UTC, JJ commented on docs/milestones.md
> +	* Esta estructura debe contener todo lo necesario para identificar a un electrodoméstico siendo especialmente relevante su consumo medio por hora.
¿De qué forma cambiar de "crear estructura" a "estructura" lo convierte en un producto?

2022-10-12 09:51 UTC, luistf24 commented on docs/milestones.md
> +	* Esta estructura debe contener todo lo necesario para identificar a un electrodoméstico siendo especialmente relevante su consumo medio por hora.
Buenas me he visto el vídeo y me he leído la presentación, en la presentación aparece como un [producto informático](https://jj.github.io/IV/preso/pmv.html#/5/0/5) , además como tiene un ámbito determinado y creo que implementa una lógica de negocio,  pensaba que era un PMV. Si no es así la verdad es que no me ha quedado muy claro.

2022-10-12 10:53 UTC, JJ commented on docs/milestones.md
> +	* Esta estructura debe contener todo lo necesario para identificar a un electrodoméstico siendo especialmente relevante su consumo medio por hora.
Consulta por favor el guión de este objetivo y la presentación que hicimos en clase.

2022-10-13 11:23 UTC, luistf24 commented
@JJ, listo para revisión

2022-10-13 11:42 UTC, JJ requested changes
El resto también, por favor concreta qué es lo que los hace un producto y qué es lo que los hace viables.

2022-10-13 11:42 UTC, JJ commented on docs/milestones.md
> +* [ ] **[M1]** Diseño de unos métodos en distintos ficheros que permitan:
Di como tienen que estar estructurados estos ficheros para que constituyan un producto.

2022-10-13 12:00 UTC, JJ approved these changes
No tengo muy claro que la secuencia sea la correcta, pero sirve para empezar a trabajar.

2022-10-13 15:17 UTC, merged