[IV-22-23] Objetivo 3
luistf24/Trozo-de-panceta pull request #39
Opened 2022-11-14 16:42 UTC by luistf24

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?

2022-11-14 18:54 UTC, luistf24 commented
Buenas @JJ ! Listo para revisión

2022-11-15 08:47 UTC, JJ commented
>     * [x]  ¿Hemos justificado correctamente en caso de elegir un gestor de
>       dependencias el que se use como gestor de tareas?
> 

No has hecho esto. ¿Por qué lo marcas?

2022-11-15 08:48 UTC, JJ requested changes
No mencionas el gestor de dependencias, y ni siquiera intentas justificar el gestor de tareas elegido. Por favor, repasa el guión (y errores frecuentes) y síguelo.

2022-11-15 08:49 UTC, JJ commented on Makefile
> +MAIN = ./cmd/trozo-de-panceta/main.go
No vamos a tener ningún main por lo pronto.

2022-11-15 08:50 UTC, JJ commented on Makefile
> +	go vet ./...
Esto hace bastante más que comprobar la sintaxis.

2022-11-15 08:51 UTC, luistf24 commented
> No mencionas el gestor de dependencias, y ni siquiera intentas justificar el gestor de tareas elegido. Por favor, repasa el guión (y errores frecuentes) y síguelo.

Lo he mencionado en los commit, pero me pongo con ello en el issue :ok_hand:

2022-11-15 08:52 UTC, luistf24 commented on Makefile
> +MAIN = ./cmd/trozo-de-panceta/main.go
Lo corrijo

2022-11-15 08:57 UTC, luistf24 commented on Makefile
> +	go vet ./...
Me pongo a buscar una alternativa

2022-11-15 11:15 UTC, JJ requested changes
No veo ningún cambio. Sigue sin explicarse el task manager ni mencionarse el gestor de dependencias.

2022-11-15 11:15 UTC, JJ commented on Makefile
> +help:
`make` hace esto automáticamente, con una opción (que ahora no recuerdo, la verdad)

2022-11-15 11:16 UTC, JJ commented on Makefile
> +MAIN =
Jolines, bórralo del todo...

2022-11-15 11:31 UTC, luistf24 commented on Makefile
> +help:
Lo busco :ok_hand:

2022-11-15 11:31 UTC, luistf24 commented on Makefile
> +MAIN =
:ok_hand:

2022-11-15 11:32 UTC, luistf24 commented
> No veo ningún cambio. Sigue sin explicarse el task manager ni mencionarse el gestor de dependencias.

Lo he puesto en los issues #37 y #38

2022-11-15 13:11 UTC, JJ commented
> > No veo ningún cambio. Sigue sin explicarse el task manager ni mencionarse el gestor de dependencias.
> 
> Lo he puesto en los issues #37 y #38

Repito que lo que queráis que evalúe tiene que estar en el PR.

2022-11-15 13:25 UTC, luistf24 commented
> > > No veo ningún cambio. Sigue sin explicarse el task manager ni mencionarse el gestor de dependencias.
> > 
> > 
> > Lo he puesto en los issues #37 y #38
> 
> Repito que lo que queráis que evalúe tiene que estar en el PR.

Aah, disculpe, lo desconocía

2022-11-15 13:31 UTC, JJ commented
> **Task manager:** De todas las alternativas que se ofrecen, me he decantado por GNU Make, es un gestor de tareas muy potente, muy utilizado, fácil de usar y viene por defecto en muchas distribuciones de linux, además creo que me ofrece todo lo necesario para poder automatizar mi proyecto
> 
> **Gestor de dependencias:** Me he decantado por Go Modules, está disponible para versiones de Go >= 1.16 y permite tener un control de las versiones de las dependencias, automatizar su instalación y limpiarlas cuando se dejan de usar de una forma muy fácil

En el *código* o texto que pongáis en el PR.

En todo caso, esto que pones tampoco corresponde a lo solicitado. Mira por favor los errores frecuentes, de la semana 8 sobre todo.

2022-11-15 16:24 UTC, JJ requested changes
Por favor, mira los errores frecuentes. No puedes seleccionar nada ni tomar ninguna decisión si no dices antes los parámetros que informan a esa decisión objetivamente, como expliqué en clase el viernes.

2022-11-15 16:24 UTC, JJ commented on docs/gestor-de-tareas.md
> +Para automatizar las tereas he mirado distintos gestores de tareas:
Los criterios de búsqueda y evaluación deben ser lo primero que se ponga.

2022-11-22 07:26 UTC, luistf24 commented
Buenas @JJ, listo para revisión

2022-11-22 07:50 UTC, JJ requested changes
Os he explicado en clase repetidamente el contenido de este objetivo y de qué se trata. Por favor, trata de entenderlo y actuar en consecuencia.
Te pueden ayudar las presentaciones que he hecho en clase, además de los errores frecuentes.

2022-11-22 07:50 UTC, JJ commented on Makefile
> +	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done
😵‍💫

2022-11-22 07:50 UTC, JJ commented on docs/gestor-de-dependencias.md
> +Para el gestor de dependencias he elegido Go Modules, está disponible para versiones de Go >= 1.16 y permite tener un control de las versiones de las dependencias, automatizar su instalación y limpia
Creo que os lo he dicho varias veces. No me contéis lo que habéis elegido. Esto no es un TFG. 
Este objetivo trata de probar si tenéis madurez para tomar una serie de decisiones técnicas. Decir qué decisión habéis tomado sin contexto no prueba de ninguna forma vuestra madurez en ese sentido.

2022-11-22 07:50 UTC, JJ commented on docs/gestor-de-tareas.md
> +El lenguaje que he utilizado para el proyecto es Go, por lo que el gestor de tareas a buscar, se tiene que ajustar a dicho lenguaje como sería en que no haya problemas con la jerarquía del proyecto,
Los gestores de tareas no se tienen que ajustar a ningún lenguaje.

2022-11-22 07:50 UTC, JJ commented on docs/gestor-de-tareas.md
> +- **Mask:**  Mask es un gestor de tareas que está en markdown y este es uno de sus puntos fuertes, además al estar escrito en Rust su instalación es muy sencilla usando cargo, se le puede inyectar có
No *está en Markdown*. ¿Es relevante esto que cuentas para elegirlo o no?

2022-11-22 07:50 UTC, JJ commented on docs/gestor-de-tareas.md
> +Al final me decanté por **Make**, es algo más complejo que Task pero quizá porque ya venía de haberlo usado antes, me ha resultado mucho más comodo usarlo, y si bien tiene esa complejidad extra en mu
Si la "complejidad" es el criterio que vas a usar, enúncialo desde el principio

2022-11-22 08:06 UTC, luistf24 commented
> Os he explicado en clase repetidamente el contenido de este objetivo y de qué se trata. Por favor, trata de entenderlo y actuar en consecuencia. Te pueden ayudar las presentaciones que he hecho en clase, además de los errores frecuentes.

Me pongo con ello :ok_hand:

2022-11-22 08:27 UTC, luistf24 commented
Buenas @JJ, ya he corregido lo comentado

2022-11-22 12:32 UTC, JJ commented on docs/gestor-de-tareas.md
> +Al final me decanté por **Make**, es algo más complejo que Task pero quizá porque ya venía de haberlo usado antes, me ha resultado mucho más comodo usarlo, y si bien tiene esa complejidad extra en mu
:arrow_up:

2022-11-22 12:41 UTC, JJ requested changes
Luis, por favor, revisa todos los comentarios. No he visto ningún cambio sustancial. En la gestión de dependencias, creo que lo que tendrías que hacer es estudiar cómo funciona la gestión de dependencias en Go y simplemente decir que no existe, como tal, un gestor de dependencias.
`go dep` está obsoleto y no tienes más que mirar el repositorio, ahí lo dice. Simplemente mira un poco de lo que hablas, y prueba que realmente estás entendiendo el concepto y examinando y considerando de forma objetiva las diferentes opciones.

2022-11-22 12:41 UTC, JJ commented on docs/gestor-de-dependencias.md
> +Los gestores de dependencias más usados en go son: **Vendoring**, **Dep** y **Go Modules**
Ya te lo he dicho varias veces. Los criterios primero. Si "hacer upgrade y downgrade" es lo que quieres que haga, y quieres que sea simple, tendrás que ponerlo como criterio.

2022-11-22 12:41 UTC, JJ commented on docs/gestor-de-dependencias.md
> +Me he decantado por **Go Modules** ya que con **Vendoring** hacer upgrade y downgrade de un paquete puede ser muy complejo, puede no funcionar para las versiones de algunos paquetes e incrementa el t
Deberías poner un enlace. Creo que `vendoring` ni siquiera es un gestor de dependencias, es un comando de `go`.  En general, es un procedimiento para trabajar con módulos. Es decir, no corresponde a lo que se pide aquí.

2022-11-22 12:41 UTC, JJ commented on docs/gestor-de-tareas.md
> +El lenguaje que he utilizado para el proyecto es Go, de los gestores de tareas que he buscado, los más destacables son:
Ya te lo he dicho varias veces. Empezar por "los más destacables" es incorrecto. Hay que comenzar con los criterios que vas a usar para buscarlos y elegirlos y los requisitos que tienen que cumplir.

2022-11-23 16:07 UTC, luistf24 commented
Buenas @JJ , listo para revisión

2022-11-23 17:11 UTC, JJ requested changes
Una de las partes ya la has solucionado, pero queda un comentario sobre el que no has hecho nada.

2022-11-23 17:11 UTC, JJ commented on docs/gestor-de-tareas.md
> +Al final me decanté por **Make**, es algo más complejo que Task pero quizá porque ya venía de haberlo usado antes, me ha resultado mucho más comodo usarlo, y si bien tiene esa complejidad extra en mu
:arrow_up:

2022-11-23 17:11 UTC, JJ commented on docs/gestor-de-dependencias.md
> +Para usarlo: ``go mod tidy``
... `por ejemplo`

2022-11-23 18:56 UTC, luistf24 commented
Buenas @jj creo que ya, pero no sé muy bien porque no me sale outdated en la primera correción

2022-11-23 19:03 UTC, JJ requested changes
En todo caso, tratad de poner criterios que sean objetivos y tengan cierto sentido. Y sobre todo que sirvan para no aumentar la deuda técnica. No busquéis criterios aleatorios (como "complejidad") y difícilmente medibles (como "popularidad" u, otra vez, "complejidad") para justificar lo que ya habéis elegido de antemano.
Y sobre todo, nada dice "estoy escribiendo cosas aquí porque me lo piden pero en realidad no he usado esto" como poner dos criterios de elección ("complejidad" y "herramientas que ofrece", sea lo que sea eso) y luego mencionar solo uno ("complejidad")
Recuerda que no se se trata de "acertar" (`make`  es una buena elección, siempre). Sino de que demostréis que sois capaces de tomar decisiones técnicas que añadan valor al cliente.

2022-11-23 19:08 UTC, luistf24 commented on docs/gestor-de-tareas.md
> +En la búsqueda me he centrado en cualquier gestor de tareas que pueda utilizar con go y la elección la he tomado en base a su complejidad y a las herramientas que ofrecen.
Reglas de dependencia, macros y suffix rules

2022-11-23 19:17 UTC, JJ commented on docs/gestor-de-tareas.md
> +En la búsqueda me he centrado en cualquier gestor de tareas que pueda utilizar con go y la elección la he tomado en base a su complejidad y a las herramientas que ofrecen.
No son herramientas, son funcionalidades. "A lo mejor luego si" es la fórmula perfecta para introducir deuda técnica.
Puedes usar perfectamente las reglas de sufijos. No creo que tenga reglas por defecto para go (tiene, si mal no recuerdo, para C, C++  y ¿Fortran?)

2022-11-24 12:17 UTC, luistf24 commented
Buenas @JJ, listo para revisión

2022-11-24 13:11 UTC, merged