[IV-22-23] Objetivo 4
luistf24/Trozo-de-panceta pull request #42
Opened 2022-11-26 08:33 UTC by luistf24

2022-12-11 17:33 UTC, JJ commented
¿Esto sigue en borrador?

2022-12-11 17:41 UTC, luistf24 commented
> ¿Esto sigue en borrador?

Buenas @JJ!En principio no, pero se me olvidó cambiarlo, disculpe las molestias

2022-12-11 17:47 UTC, luistf24 commented
Listo para revisión @JJ

2022-12-11 18:37 UTC, JJ requested changes
El principal problema es que no hay implementación de la lógica de negocio, que es lo fundamental y os dije desde el objetivo cero. El resto también tiene su importancia, pero no tanta.

2022-12-11 18:37 UTC, JJ commented on docs/biblioteca-de-aserciones.md
> +En la búsqueda me he centrado en enontrar las bibliotecas más usadas y el criterio para la elección es lo extendido que esté su uso.
No es un criterio objetivo, ni has mostrado que lo hayas medido.

2022-12-11 18:37 UTC, JJ commented on internal/light_info.go
> +	Tramo0 Price `json:"00-01"`
Seguro que hay una forma más simple de hacer esto...

2022-12-11 18:37 UTC, JJ commented on internal/light_info.go
> +	response, err := http.Get("https://api.preciodelaluz.org/v1/prices/all?zone=PCB")
No es nunca una buena idea descargarse las cosas directamente dentro del programa. Para empezar, porque te la vas a descargar un montón de veces (tests, pruebas y demás), pero para seguir porque el URL puede cambiar y tú lo que tienes que obtener es simplemente el resultado.
En ese sentido, relacionado con lo de arriba, deberías descargarte la información previamente en un formato que sea fácil de leer por Go, pero lo más importante, que puedas usar para test repetidamente. Te recuerdo que para test no tienes por qué usar la información real.

2022-12-11 18:37 UTC, JJ commented on internal/light_info.go
> +		fmt.Print("Un error ha ocurrido")
Los errores deben ser informativos, y diseñarse de la misma forma que las clases. Busca las mejores prácticas en errores en este lenguaje.

2022-12-11 18:37 UTC, JJ commented on internal/light_info.go
> +	l.brackets[0] = responseObject.Tramo0.Precio
Esto no lo puedes hacer, de verdad.

2022-12-11 18:37 UTC, JJ commented on internal/light_info.go
> +func (l *LightInfo) generateTimeBracketList() [24]TimeBracket {
No hay ninguna implementación de la lógica de negocio aquí.

2022-12-11 18:40 UTC, luistf24 commented
> El principal problema es que no hay implementación de la lógica de negocio, que es lo fundamental y os dije desde el objetivo cero. El resto también tiene su importancia, pero no tanta.

Me pongo con ello :ok_hand:

2022-12-12 16:51 UTC, luistf24 commented
Listo para revisión @JJ

2022-12-12 17:50 UTC, JJ requested changes
Una vez más, no veo la lógica de negocio, pero el problema es de planteamiento, porque realmente no has planteado un issue con el problema que tienes que resolver. Por favor, replantea los issues correspondientes, y empeza a desarrollar la lógica de negocio que resuelva el problema del usuario.

2022-12-12 18:37 UTC, luistf24 commented
> Una vez más, no veo la lógica de negocio, pero el problema es de planteamiento, porque realmente no has planteado un issue con el problema que tienes que resolver. Por favor, replantea los issues correspondientes, y empeza a desarrollar la lógica de negocio que resuelva el problema del usuario.

Me pongo con ello, pero tengo una duda, ¿Si no tengo una historia de usuario asociada a este Milestone, la creo o desplazo a este alguna de las que tengo?

2022-12-12 18:48 UTC, luistf24 commented
> > > Una vez más, no veo la lógica de negocio, pero el problema es de planteamiento, porque realmente no has planteado un issue con el problema que tienes que resolver. Por favor, replantea los issues correspondientes, y empeza a desarrollar la lógica de negocio que resuelva el problema del usuario.
> > 
> > 
> > Me pongo con ello, pero tengo una duda, ¿Si no tengo una historia de usuario asociada a este Milestone, la creo o desplazo a este alguna de las que tengo?
> 
> Ya os expliqué varias veces que las historias de usuario son ortogonales a los _milestones_; los issues son los que se asignan a milestones, y las historias de usuario tendrán que moverse al milestone donde estén desarrollandose _sus_ issues.
> 
> En todo caso, recuerda que en desarrollo ágil lo importante es satisfacer al usuario, y por tanto siempre hay que estar trabajando con una historia de usuario (o varias). Los milestones sirven para organizar el desarrollo, pero donde se sabe qué hay que desarrollar es en las historias de usuario. De las dos cosas que hay que saber en desarrollo ágil, qué hago ahora y si lo que hago está bien, las historias de usuario responden a lo segundo. Lo primero simplemente ayuda a que se alcancen los objetivos en tiempo y presupuesto.

Perfecto, ahora lo tengo mucho más claro, muchas gracias!!

2022-12-17 16:11 UTC, luistf24 commented
Buenas @JJ, ya he corregido los fallos que me comentó, pero sigo teniendo problemas con la lógica de negocio, en este milestone no hay mucho que hacer relacionado con esta y me preguntaba si podía ponerme con el milestone 2 ya que en este se empieza con la lógica de negocio

2022-12-18 10:51 UTC, JJ commented
> Buenas @JJ, ya he corregido los fallos que me comentó, pero sigo teniendo problemas con la lógica de negocio, en este milestone no hay mucho que hacer relacionado con esta y me preguntaba si podía ponerme con el milestone 2 ya que en este se empieza con la lógica de negocio

En este milestone tendrías, efectivamente, que tener la lógica de negocio. Asígnalo al que veas más conveniente.

2022-12-18 17:22 UTC, luistf24 commented
> > Buenas @JJ, ya he corregido los fallos que me comentó, pero sigo teniendo problemas con la lógica de negocio, en este milestone no hay mucho que hacer relacionado con esta y me preguntaba si podía ponerme con el milestone 2 ya que en este se empieza con la lógica de negocio
> 
> En este milestone tendrías, efectivamente, que tener la lógica de negocio. Asígnalo al que veas más conveniente.

Perfecto, me pongo con ello :ok_hand:

2022-12-19 12:00 UTC, luistf24 commented
Buenas @JJ, listo para revisión

2022-12-19 13:51 UTC, JJ requested changes
El problema principal es que, aunque has incluido y testeado elementos de la lógica de negocio, realmente no has resuelto el problema con el que estés trabajando, que supongo que será el #4. Una recta de regresión no soluciona el problema (y para mi con los nombres que has usado es imposible saber de dónde sale la recta de regresión).
Más o menos está claro qu een #48 has incluido un paso intermedio, pero tendrías que avanzar más para enlazarlo realmente con lo que pide #4 (o #5, la HU que elijas para el PMV, y consideres más simple).

2022-12-19 13:51 UTC, JJ commented on api/test.json
> +
No creo que un directorio `api` sea el más adecuado para los datos de test. Quizás simplemente `data` o `test-data`

2022-12-19 13:51 UTC, JJ commented on inferencia/inferencia.go
> +func calcRR(x []float32, y[]float32)(func(int)float32, error) {
Por favor, usad nombres de verdad. Los nombres deben documentar el comportamiento y la semántica.

2022-12-19 13:51 UTC, JJ commented on inferencia/inferencia_test.go
> +	prueba = temp
Um, qué poco me gusta esto. Si prueba es una `fixture`, debes usar una función de test que garantice que es válidad antes de empezar los tests. Los tests tienen que ser independientes, y aquí estás confiando que este test se va a ejecutar antes que el otro. Si se paraleliza, por ejemplo, no va a ser así. Las fixtures se garantiza que se ejecutan antes que cualquier test.

2022-12-19 16:40 UTC, luistf24 commented on inferencia/inferencia_test.go
> +	prueba = temp
> El problema principal es que, aunque has incluido y testeado elementos de la lógica de negocio, realmente no has resuelto el problema con el que estés trabajando, que supongo que será el #4. Una recta de regresión no soluciona el problema (y para mi con los nombres que has usado es imposible saber de dónde sale la recta de regresión). Más o menos está claro qu een #48 has incluido un paso intermedio, pero tendrías que avanzar más para enlazarlo realmente con lo que pide #4 (o #5, la HU que elijas para el PMV, y consideres más simple).

Buenas @JJ, ya he cambiado lo que me ha comentado, pero tengo una duda, si avanzo más no sería meterme en el (Milestone 3)[https://github.com/luistf24/Trozo-de-panceta/milestone/11]?

2022-12-19 17:42 UTC, luistf24 commented on inferencia/inferencia_test.go
> +	prueba = temp
Pues con lo que tengo hecho ya, ya se podría predecir más o menos el precio  de la luz, se genera una recta de regresión a partir de dos arrays, uno de días y otro con el precio del tramo en cada día, pero como todavía no tengo base de datos, no se me ocurre como hacerlo

2022-12-19 19:26 UTC, JJ commented on inferencia/inferencia_test.go
> +	prueba = temp
Pues convendría que lo hicieras, porque lo que hay que hacer aquí es la lógica de negocio, básicamente.

2022-12-19 19:26 UTC, JJ commented on inferencia/inferencia_test.go
> +	prueba = temp
Una vez más, plantea el problema en un issue. Como lo hagas  no es importante, lo importante es que se siga el método adecuado para hacerlo y resulte un producto mínimamente viable.

2022-12-19 19:27 UTC, JJ commented on inferencia/inferencia_test.go
> +	prueba = temp
Si no lo testeas, es que ni siquiera sabes si el método que has planteado resuelve el problema.

2022-12-20 08:42 UTC, luistf24 commented on inferencia/inferencia_test.go
> +	prueba = temp
Me pongo con ello :ok_hand:

2022-12-20 09:21 UTC, luistf24 commented
Buenas @JJ ya he añadido los issues y un ejemplo de test siguiendo la lógica de negocio

2022-12-20 10:07 UTC, JJ requested changes
Me vas a perdonar que objete una vez más, pero realmente me resulta imposible saber si has implementado la lógica de negocio y cómo. En parte es por la denominación de los métodos, que corresponden a la implementación, no al dominio del problema. Pero también me resulta complicado seguir qué se está haciendo y dónde, efectivamente, se testea #4 o #10

2022-12-20 10:07 UTC, JJ commented on inferencia/inferencia.go
> + *	salida[0] -> Media de X
Deberías haber devuelto un struct con la salida. Recuerda que las estructuras de datos tienen que usarse de forma semántica. Dos medias, dos varianzas y una covarianza *no son* un array de 5 elementos.

2022-12-20 10:07 UTC, JJ commented on inferencia/inferencia.go
> +func calculateRegressionLine(x []float32, y[]float32)(func(int)float32, error) {
Los nombres tienen que corresponder a la función, no a la implementación. A #9 le interesa saber la hora óptima, no una curva de regresión. DDD trata de que exista el mismo vocabulario en el dominio del problema y el programa. Si te piden "hora óptima" no le puedes contestar "Toma, una línea de regresión".

2022-12-20 10:07 UTC, JJ commented on inferencia/inferencia_test.go
> +func TestCalcReq(t *testing.T) {
Por definición, un fixture no puede tener errores (ni se testea, es un fixture)

2022-12-20 10:07 UTC, JJ commented on internal/light_info.go
> +func (l *LightInfo) generateTimeBracket(i int) (TimeBracket, error) {
Por favor, sigue las mejores prácticas usando nombres de  variables significativos.

2022-12-20 10:32 UTC, luistf24 commented
> Me vas a perdonar que objete una vez más, pero realmente me resulta imposible saber si has implementado la lógica de negocio y cómo. En parte es por la denominación de los métodos, que corresponden a la implementación, no al dominio del problema. Pero también me resulta complicado seguir qué se está haciendo y dónde, efectivamente, se testea #4 o #10

Entiendo, me pongo con ello :ok_hand:

2022-12-20 11:12 UTC, luistf24 commented
Ya he realizado los cambios @JJ

2022-12-21 09:17 UTC, JJ approved these changes
Voy a darlo por bueno, porque te lo has currado y además has tenido muy buena disposición a hacerlo. En todo caso, mira los comentarios que te he hecho, sobre todo relativos al uso de docstrings y a código que realmente parece que no está relacionado con la lógica de negocio.

2022-12-21 09:17 UTC, JJ commented on inferencia/inferencia.go
> + *	x -> Array con los días desde que empezo almacenarse los días (0,1,...)
¿Es este el formato para los docstrings en Go? ¿con la -> y eso? ¿Sin tipos?

2022-12-21 09:17 UTC, JJ commented on inferencia/inferencia.go
> +func calculatePredictFunction(x []float32, y[]float32)(func(int)float32, error) {
Una forma curiosa de encapsular datos en una función, devolver una función con ellos. Supongo que será el equivalente no-PDO de un objeto. :clap:

2022-12-21 09:17 UTC, JJ commented on internal/light_info.go
> +func (l *LightInfo) generateTimeBracket(tramo int) (TimeBracket, error) {
Me da la impresión de que esto no lo estás usando.

2022-12-21 09:28 UTC, luistf24 commented on inferencia/inferencia.go
> + *	x -> Array con los días desde que empezo almacenarse los días (0,1,...)
La verdad es que no es la correcta, lo cambio por [esta](https://go.dev/blog/godoc) :ok_hand:

2022-12-21 09:37 UTC, merged